spring:
  application:
    name: spring-mcp-server
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
  ai:
    mcp:
      server:
        name: spring-clinic-mcp-server
        version: 0.0.1
        sse-endpoint: /sse
  # NOTE: You must disable the banner and the console logging
  # to allow the STDIO transport to work !!!
  main:
    banner-mode: off
logging:
  #pattern:
    #console:
  file:
    name: ./spring-mcp-server.log